--- #YAML:1.0
name:                PDF-API2
version:             0.69
abstract:            TheNextGen PDF Create/Modify API
license:             ~
author:              
    - areibens@cpan.org
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Compress::Zlib:                1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
