#!/usr/bin/perl -w

use PDF::API2;

$pdf=PDF::API2->new;

$f1=$pdf->corefont('Helvetica',1);

foreach $fn (qw(
	Courier-Bold
	Courier-BoldOblique
	Courier-Oblique
	Courier
	Helvetica-Bold
	Helvetica-BoldOblique
	Helvetica-Oblique
	Helvetica
	Symbol
	Times-Bold
	Times-BoldItalic
	Times-Italic
	Times-Roman
	ZapfDingbats
)) {

	$font=$pdf->corefont($fn,1);
	
	$page = $pdf->page;
	$page->mediabox(595,842);
	$txt=$page->text;
	$txt->compress;
	$txt->translate(100,700);
	$txt->font($font,50);
	$txt->lead(50);
	$txt->text('Hello World !');
	$txt->cr;
	$txt->font($f1,20);
	$txt->text("This is font: $fn");

	$txt->font($font,20);

	foreach $x (0..15) {
		foreach $y (0..15) {
			$txt->translate(50+(33*$x),50+(33*$y));
			$txt->text(chr($y*16+$x));
		}
	}

}

$pdf->saveas("$0.pdf");

exit;

__END__
