#=======================================================================
#         _   _    :    ____  ____  _____      _    ____ ___   ____
#     _  |_|_|_|   :   |  _ \|  _ \|  ___|    / \  |  _ \_ _| |___ \
#    |_| _|_||_|   :   | |_) | | | | |_      / _ \ | |_) | |    __) |
#    _  |_||_|_|   :   |  __/| |_| |  _|    / ___ \|  __/| |   / __/
#   |_|  |_|_|_|   :   |_|   |____/|_|     /_/   \_\_|  |___| |_____|
#                  : 
#=======================================================================
package PDF::API2::Version;
BEGIN {
    use vars qw( $VERSION %CVersion );
    $VERSION = '0.55';
    %CVersion = (
        'vFredo' => 'PDF::API2 0.55 (fix-3328 / 2006-08-14)',
        'vGNU' => 'PDF::API2 0.55 (2006-08-14 20:15:07)',
        'vHex' => '0x00037D00',
        'vLong' => '0.55 (2006-08-14 20:15:07)',
        'vPerl' => '0.55',
        'vShort' => '0.55',
        'vSquid' => '0.55-fix-3328',
        'vTeX' => 'This is PDF::API2, Version 0.55 (2006-08-14 20:15:07)',
        'vWeb' => 'PDF::API2/0.55',
        'vWin' => '0.55 build 3328',
    );
}
1;

__END__
# autogenerated file -- do not edit.

=pod

=head1 NAME

PDF::API2::Version

=head1 VERSION

  vFredo: PDF::API2 0.55 (fix-3328 / 2006-08-14) 
    vGNU: PDF::API2 0.55 (2006-08-14 20:15:07) 
    vHex: 0x00037D00 
   vLong: 0.55 (2006-08-14 20:15:07) 
   vPerl: 0.55 
  vShort: 0.55 
  vSquid: 0.55-fix-3328 
    vTeX: This is PDF::API2, Version 0.55 (2006-08-14 20:15:07) 
    vWeb: PDF::API2/0.55 
    vWin: 0.55 build 3328 

=cut

