#=======================================================================
#         _   _    :    ____  ____  _____      _    ____ ___   ____
#     _  |_|_|_|   :   |  _ \|  _ \|  ___|    / \  |  _ \_ _| |___ \
#    |_| _|_||_|   :   | |_) | | | | |_      / _ \ | |_) | |    __) |
#    _  |_||_|_|   :   |  __/| |_| |  _|    / ___ \|  __/| |   / __/
#   |_|  |_|_|_|   :   |_|   |____/|_|     /_/   \_\_|  |___| |_____|
#                  : 
#=======================================================================
package PDF::API2::Version;
BEGIN {
    use vars qw( $VERSION %CVersion );
    $VERSION = '0.40.91';
    %CVersion = (
        'vFredo' => 'PDF::API2 0.40.91 (stable-3419 / 2005-02-14)',
        'vGNU' => 'PDF::API2 0.40.91 (2005-02-14 21:10:18)',
        'vHex' => '0x00028D5B',
        'vLong' => '0.40.91 (2005-02-14 21:10:18)',
        'vPerl' => '0.40.91',
        'vShort' => '0.40.91',
        'vSquid' => '0.40-stable-3419',
        'vTeX' => 'This is PDF::API2, Version 0.40.91 (2005-02-14 21:10:18)',
        'vWeb' => 'PDF::API2/0.40.91',
        'vWin' => '0.40 build 3419',
    );
}
1;

__END__
# autogenerated file -- do not edit.

=pod

=head1 NAME

PDF::API2::Version

=head1 VERSION

  vFredo: PDF::API2 0.40.91 (stable-3419 / 2005-02-14) 
    vGNU: PDF::API2 0.40.91 (2005-02-14 21:10:18) 
    vHex: 0x00028D5B 
   vLong: 0.40.91 (2005-02-14 21:10:18) 
   vPerl: 0.40.91 
  vShort: 0.40.91 
  vSquid: 0.40-stable-3419 
    vTeX: This is PDF::API2, Version 0.40.91 (2005-02-14 21:10:18) 
    vWeb: PDF::API2/0.40.91 
    vWin: 0.40 build 3419 

=cut

