#=======================================================================
#         _   _    :    ____  ____  _____      _    ____ ___   ____
#     _  |_|_|_|   :   |  _ \|  _ \|  ___|    / \  |  _ \_ _| |___ \
#    |_| _|_||_|   :   | |_) | | | | |_      / _ \ | |_) | |    __) |
#    _  |_||_|_|   :   |  __/| |_| |  _|    / ___ \|  __/| |   / __/
#   |_|  |_|_|_|   :   |_|   |____/|_|     /_/   \_\_|  |___| |_____|
#                  : 
#=======================================================================
package PDF::API2::Version;
BEGIN {
    use vars qw( $VERSION %CVersion );
    $VERSION = '0.57';
    %CVersion = (
        'vFredo' => 'PDF::API2 0.57 (fix-3328 / 2007-01-04)',
        'vGNU' => 'PDF::API2 0.57 (2007-01-04 18:47:06)',
        'vHex' => '0x00039D00',
        'vLong' => '0.57 (2007-01-04 18:47:06)',
        'vPerl' => '0.57',
        'vShort' => '0.57',
        'vSquid' => '0.57-fix-3328',
        'vTeX' => 'This is PDF::API2, Version 0.57 (2007-01-04 18:47:06)',
        'vWeb' => 'PDF::API2/0.57',
        'vWin' => '0.57 build 3328',
    );
}
1;

__END__
# autogenerated file -- do not edit.

=pod

=head1 NAME

PDF::API2::Version

=head1 VERSION

  vFredo: PDF::API2 0.57 (fix-3328 / 2007-01-04) 
    vGNU: PDF::API2 0.57 (2007-01-04 18:47:06) 
    vHex: 0x00039D00 
   vLong: 0.57 (2007-01-04 18:47:06) 
   vPerl: 0.57 
  vShort: 0.57 
  vSquid: 0.57-fix-3328 
    vTeX: This is PDF::API2, Version 0.57 (2007-01-04 18:47:06) 
    vWeb: PDF::API2/0.57 
    vWin: 0.57 build 3328 

=cut

